-- Già applicato tramite migration_security_fixes.sql.
-- Le RPC admin_list_users e admin_count_users sono ristrette a service_role
-- con le firme corrette (int, int, text, text, text) e (text, text, text).
-- Questo file è mantenuto solo come documentazione dell'intenzione.
